name: DadMEGA
favicon: null
layout_spectrum: 0.6894750089850277
typography_spectrum: 0.1787706771865487
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#feffff'
    - '#704e1b'
    - '#040404'
    - '#ffa45a'
    - '#39c773'
  brandStrength: 0.17324188887141645
  lightness: 0.9375
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
