name: DadMEGA
favicon: null
layout_spectrum: 0.6894750089850277
typography_spectrum: 0.1787706771865487
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.17324188887141645
  lightness: 0.4407562066335231
  saturation: 0.7723542710300535
  rhythmicContrast: 0.6661477752495557
purpose: []
